### ISSUE TITLE
[종합] 전체 페이지 수정 사항

### ISSUE THREAD

**Issue by yoorli** [Docthru/docthru-fe#68]
## 구현할 기능:
전체 페이지 테스트 후 수정 및 개선 사항 적어주세요

### 해야할일
- [x] 로고 클릭 시 경로 수정 - admin
- [x] nav에서 해당 페이지일 때 강조 표시 (글자색 진하게 등)
- [x] ![image](https://github.com/user-attachments/assets/eb906ca0-3e8a-4a09-8228-86583fa09222)
- [x] Feedback 관련, 답글 생성시에는 바로 반영되는데 수정, 삭제시 바로 반영안됨.
- [x] 프로필 컴포넌트에서 닉네임 클릭시 /profile/{userid}
- [x] 기존 도전하지않은 챌린지 신청할경우 -> 웹에디터 페이지에서 랜딩으로 바로 리다이렉팅되는 오류
- [x] 도전계속하기 -> 포기하기 버튼 누르면 id가 안보내진다.
- [ ] 작업물 제출 및, 여타 제출사항관련 버튼 isLoading or debouncing 필요할듯?

**Comment by claudia99503** [comment]
- [ ] 회원가입, 로그인 페이지 => 입력칸 `border`가 경우에 따라 나타나거나 사라짐
